# Generated by Django 6.0.6 on 2026-07-01 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('overall_score', models.IntegerField(blank=True, null=True)),
                ('score_band', models.CharField(blank=True, choices=[('good', 'Good'), ('warn', 'Needs work'), ('poor', 'Poor')], max_length=10)),
                ('score_label', models.CharField(blank=True, max_length=150)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('on_page', 'On-Page'), ('technical', 'Technical'), ('performance', 'Performance')], max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('warn', 'Warning'), ('fail', 'Fail')], max_length=10)),
                ('detail', models.TextField(blank=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='audits.audit')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
