# Generated by Django 6.0.6 on 2026-07-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkresult',
            name='recommendation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='checkresult',
            name='category',
            field=models.CharField(choices=[('on_page', 'On-Page'), ('technical', 'Technical'), ('social', 'Social Metadata'), ('links', 'Links'), ('performance', 'Performance')], max_length=20),
        ),
    ]
